"""leaderboard gender

Revision ID: 1ae5bd90e22b
Revises: 128d5b0baedb
Create Date: 2025-02-06 17:47:05.700306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ae5bd90e22b'
down_revision: Union[str, None] = '128d5b0baedb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leaderboard', sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='gendertype'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leaderboard', 'gender')
    # ### end Alembic commands ###
