"""team fix

Revision ID: 73af32e739e2
Revises: d643c8c0e420
Create Date: 2025-02-05 14:22:10.576369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73af32e739e2'
down_revision: Union[str, None] = 'd643c8c0e420'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='gendertype'), nullable=False),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('points_scored', sa.Integer(), nullable=True),
    sa.Column('points_conceded', sa.Integer(), nullable=True),
    sa.Column('current_position', sa.Integer(), nullable=True),
    sa.Column('win_percentage', sa.Float(), nullable=True),
    sa.Column('points_difference', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
    op.add_column('games', sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='gendertype'), nullable=False))
    op.drop_column('games', 'status')
    op.drop_column('games', 'sex')
    op.add_column('players', sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='gendertype'), nullable=False))
    op.add_column('players', sa.Column('total_points', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('total_rebounds', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('total_assists', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('total_steals', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('total_blocks', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('total_turnovers', sa.Integer(), nullable=True))
    op.drop_column('players', 'points_per_game')
    op.drop_column('players', 'rebounds_per_game')
    op.drop_column('players', 'assists_per_game')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('assists_per_game', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('players', sa.Column('rebounds_per_game', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('players', sa.Column('points_per_game', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('players', 'total_turnovers')
    op.drop_column('players', 'total_blocks')
    op.drop_column('players', 'total_steals')
    op.drop_column('players', 'total_assists')
    op.drop_column('players', 'total_rebounds')
    op.drop_column('players', 'total_points')
    op.drop_column('players', 'gender')
    op.add_column('games', sa.Column('sex', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('games', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('games', 'gender')
    op.drop_index(op.f('ix_teams_id'), table_name='teams')
    op.drop_table('teams')
    # ### end Alembic commands ###
